-- MySQL Script generated by MySQL Workbench
-- Thu Sep 11 02:15:31 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Pizzeria
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Pizzeria` ;

-- -----------------------------------------------------
-- Schema Pizzeria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Pizzeria` DEFAULT CHARACTER SET utf8 ;
USE `Pizzeria` ;

-- -----------------------------------------------------
-- Table `Provinces`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Provinces` ;

CREATE TABLE IF NOT EXISTS `Provinces` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Localities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Localities` ;

CREATE TABLE IF NOT EXISTS `Localities` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `province_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `province_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_province_idx` (`province_id` ASC) VISIBLE,
  CONSTRAINT `fk_province`
    FOREIGN KEY (`province_id`)
    REFERENCES `Provinces` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Customers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Customers` ;

CREATE TABLE IF NOT EXISTS `Customers` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `surname` VARCHAR(100) NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  `zip_code` VARCHAR(10) NOT NULL,
  `locality_id` INT UNSIGNED NOT NULL,
  `phone` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `locality_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_locality_idx` (`locality_id` ASC) VISIBLE,
  CONSTRAINT `fk_locality`
    FOREIGN KEY (`locality_id`)
    REFERENCES `Localities` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Stores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Stores` ;

CREATE TABLE IF NOT EXISTS `Stores` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `address` VARCHAR(255) NOT NULL,
  `zip_code` VARCHAR(10) NOT NULL,
  `locality_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `locality_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_store_locality_idx` (`locality_id` ASC) VISIBLE,
  CONSTRAINT `fk_store_locality`
    FOREIGN KEY (`locality_id`)
    REFERENCES `Localities` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Employees`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Employees` ;

CREATE TABLE IF NOT EXISTS `Employees` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `surname` VARCHAR(100) NOT NULL,
  `nif` VARCHAR(10) NOT NULL,
  `phone` VARCHAR(15) NOT NULL,
  `role` ENUM('delivery man', 'cooks') NOT NULL,
  `store_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `store_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_employee_store_idx` (`store_id` ASC) VISIBLE,
  CONSTRAINT `fk_employee_store`
    FOREIGN KEY (`store_id`)
    REFERENCES `Stores` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Orders` ;

CREATE TABLE IF NOT EXISTS `Orders` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `date` DATE NOT NULL,
  `total_price` DECIMAL(6,2) UNSIGNED NOT NULL,
  `delivery` ENUM('delivery', 'collect') NOT NULL,
  `customer_id` INT UNSIGNED NOT NULL,
  `store_id` INT UNSIGNED NOT NULL,
  `delivered_by` INT UNSIGNED NULL,
  `delivery_time` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_customer_idx` (`customer_id` ASC) VISIBLE,
  INDEX `fk_store_idx` (`store_id` ASC) VISIBLE,
  INDEX `fk_delivery_idx` (`delivered_by` ASC) VISIBLE,
  CONSTRAINT `fk_customer`
    FOREIGN KEY (`customer_id`)
    REFERENCES `Customers` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_store`
    FOREIGN KEY (`store_id`)
    REFERENCES `Stores` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_delivery`
    FOREIGN KEY (`delivered_by`)
    REFERENCES `Employees` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizza Categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pizza Categories` ;

CREATE TABLE IF NOT EXISTS `Pizza Categories` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Products` ;

CREATE TABLE IF NOT EXISTS `Products` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(55) NOT NULL,
  `description` TEXT NOT NULL,
  `image` BLOB NULL,
  `price` DECIMAL(4,2) UNSIGNED NOT NULL,
  `type` ENUM('pizza', 'burguer', 'drink') NOT NULL,
  `pizza_category_id` INT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_categories_idx` (`pizza_category_id` ASC) VISIBLE,
  CONSTRAINT `fk_categories`
    FOREIGN KEY (`pizza_category_id`)
    REFERENCES `Pizza Categories` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Orders_products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Orders_products` ;

CREATE TABLE IF NOT EXISTS `Orders_products` (
  `order_id` INT UNSIGNED NOT NULL,
  `product_id` INT UNSIGNED NOT NULL,
  `quantity` TINYINT UNSIGNED NOT NULL,
  PRIMARY KEY (`order_id`, `product_id`),
  INDEX `fk_product_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_order`
    FOREIGN KEY (`order_id`)
    REFERENCES `Orders` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_product`
    FOREIGN KEY (`product_id`)
    REFERENCES `Products` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
