-- MySQL Script generated by MySQL Workbench
-- Fri Sep 12 17:28:16 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema youtube
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `youtube` ;

-- -----------------------------------------------------
-- Schema youtube
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `youtube` DEFAULT CHARACTER SET utf8 ;
USE `youtube` ;

-- -----------------------------------------------------
-- Table `Countries`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Countries` ;

CREATE TABLE IF NOT EXISTS `Countries` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Users` ;

CREATE TABLE IF NOT EXISTS `Users` (
  `id` INT UNSIGNED NOT NULL,
  `username` VARCHAR(50) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `birth_date` DATE NOT NULL,
  `sex` ENUM('male', 'female') NOT NULL,
  `country_id` INT UNSIGNED NOT NULL,
  `zip_code` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`, `country_id`),
  INDEX `fk_users_countries_idx` (`country_id` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  CONSTRAINT `fk_users_countries`
    FOREIGN KEY (`country_id`)
    REFERENCES `Countries` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Videos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Videos` ;

CREATE TABLE IF NOT EXISTS `Videos` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT UNSIGNED NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `description` TEXT NULL,
  `publication_date` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `size_mb` DECIMAL(10,2) UNSIGNED NOT NULL,
  `file_name` VARCHAR(255) NOT NULL,
  `duration_seconds` BIGINT UNSIGNED NOT NULL,
  `state` ENUM('public', 'hidden', 'private') NOT NULL,
  `thumbnail` VARCHAR(255) NOT NULL,
  `views` BIGINT UNSIGNED NOT NULL,
  `likes_number` BIGINT UNSIGNED NOT NULL,
  `dislikes_number` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `user_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_videos_users_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_videos_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `Users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Tags`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Tags` ;

CREATE TABLE IF NOT EXISTS `Tags` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Video_tags`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Video_tags` ;

CREATE TABLE IF NOT EXISTS `Video_tags` (
  `video_id` INT UNSIGNED NOT NULL,
  `tag_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`video_id`, `tag_id`),
  CONSTRAINT `fk_video_tags_videos`
    FOREIGN KEY (`video_id`)
    REFERENCES `Videos` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_video_tags_tags`
    FOREIGN KEY (`tag_id`)
    REFERENCES `Tags` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Channels`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Channels` ;

CREATE TABLE IF NOT EXISTS `Channels` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT UNSIGNED NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `description` TEXT NOT NULL,
  `creation_date` DATE NULL DEFAULT CURDATE(),
  PRIMARY KEY (`id`, `user_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_channels_users_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_channels_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `Users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Suscriptions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Suscriptions` ;

CREATE TABLE IF NOT EXISTS `Suscriptions` (
  `user_id` INT UNSIGNED NOT NULL,
  `channel_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`user_id`, `channel_id`),
  INDEX `fk_suscriptions_channels_idx` (`channel_id` ASC) VISIBLE,
  CONSTRAINT `fk_suscriptions_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `Users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_suscriptions_channels`
    FOREIGN KEY (`channel_id`)
    REFERENCES `Channels` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `video_reactions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `video_reactions` ;

CREATE TABLE IF NOT EXISTS `video_reactions` (
  `user_id` INT UNSIGNED NOT NULL,
  `video_id` INT UNSIGNED NOT NULL,
  `date` DATE NULL DEFAULT CURDATE(),
  `reaction` ENUM('like', 'dislike') NOT NULL,
  PRIMARY KEY (`user_id`, `video_id`),
  INDEX `fk_dislike_videos_video_idx` (`video_id` ASC) VISIBLE,
  CONSTRAINT `fk_video_reactions_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `Users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_video_reactions_video`
    FOREIGN KEY (`video_id`)
    REFERENCES `Videos` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Playlists`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Playlists` ;

CREATE TABLE IF NOT EXISTS `Playlists` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT UNSIGNED NOT NULL,
  `creation_date` DATE NULL DEFAULT CURDATE(),
  `state` ENUM('public', 'private') NOT NULL,
  PRIMARY KEY (`id`, `user_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_playlists_users_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_playlists_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `Users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Comments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Comments` ;

CREATE TABLE IF NOT EXISTS `Comments` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `text` TEXT NOT NULL,
  `date` DATE NULL DEFAULT CURDATE(),
  `user_id` INT UNSIGNED NOT NULL,
  `video_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `video_id`, `user_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_comments_users_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_comments_videos_idx` (`video_id` ASC) VISIBLE,
  CONSTRAINT `fk_comments_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `Users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_comments_videos`
    FOREIGN KEY (`video_id`)
    REFERENCES `Videos` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `comment_reactions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `comment_reactions` ;

CREATE TABLE IF NOT EXISTS `comment_reactions` (
  `user_id` INT UNSIGNED NOT NULL,
  `comment_id` INT UNSIGNED NOT NULL,
  `date` DATE NULL DEFAULT CURDATE(),
  `reaction` ENUM('like', 'dislike') NOT NULL,
  PRIMARY KEY (`user_id`, `comment_id`),
  INDEX `fk_dislike_comments_comments_idx` (`comment_id` ASC) VISIBLE,
  CONSTRAINT `fk_dislike_comments_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `Users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_dislike_comments_comments`
    FOREIGN KEY (`comment_id`)
    REFERENCES `Comments` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Playlist_videos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Playlist_videos` ;

CREATE TABLE IF NOT EXISTS `Playlist_videos` (
  `playlist_id` INT UNSIGNED NOT NULL,
  `video_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`playlist_id`, `video_id`),
  INDEX `fk_playlist_videos_videos_idx` (`video_id` ASC) VISIBLE,
  CONSTRAINT `fk_playlist_videos_playlists`
    FOREIGN KEY (`playlist_id`)
    REFERENCES `Playlists` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_playlist_videos_videos`
    FOREIGN KEY (`video_id`)
    REFERENCES `Videos` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
