-- MySQL Script generated by MySQL Workbench
-- Wed Sep 10 22:36:43 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Optical
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Optical` ;

-- -----------------------------------------------------
-- Schema Optical
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Optical` DEFAULT CHARACTER SET utf8mb4 ;
USE `Optical` ;

-- -----------------------------------------------------
-- Table `Supplier`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Supplier` ;

CREATE TABLE IF NOT EXISTS `Supplier` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(55) NOT NULL,
  `street` VARCHAR(100) NOT NULL,
  `number` VARCHAR(10) NOT NULL,
  `floor` INT NOT NULL,
  `door` VARCHAR(10) NOT NULL,
  `city` VARCHAR(50) NOT NULL,
  `zip_code` VARCHAR(10) NOT NULL,
  `country` VARCHAR(50) NOT NULL,
  `phone` VARCHAR(15) NOT NULL,
  `fax` VARCHAR(20) NOT NULL,
  `nif` VARCHAR(9) NOT NULL,
  UNIQUE INDEX `idSupplier_UNIQUE` (`id` ASC) VISIBLE,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Brand`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Brand` ;

CREATE TABLE IF NOT EXISTS `Brand` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `id_supplier` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `id_supplier`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  INDEX `fk_supplier_idx` (`id_supplier` ASC) VISIBLE,
  CONSTRAINT `fk_supplier`
    FOREIGN KEY (`id_supplier`)
    REFERENCES `Supplier` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Glasses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Glasses` ;

CREATE TABLE IF NOT EXISTS `Glasses` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_brand` INT UNSIGNED NOT NULL,
  `right_crystal_graduation` DECIMAL(4,2) NOT NULL,
  `left_crystal_graduation` DECIMAL(4,2) NOT NULL,
  `frame_type` ENUM('floating', 'paste', 'metal') NOT NULL,
  `frame_color` VARCHAR(30) NOT NULL,
  `right_lens_color` VARCHAR(30) NOT NULL,
  `left_lens_color` VARCHAR(30) NOT NULL,
  `price` DECIMAL(7,2) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `id_brand`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_brand_idx` (`id_brand` ASC) VISIBLE,
  CONSTRAINT `fk_brand`
    FOREIGN KEY (`id_brand`)
    REFERENCES `Brand` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Customers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Customers` ;

CREATE TABLE IF NOT EXISTS `Customers` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `zip_code` VARCHAR(10) NOT NULL,
  `phone` VARCHAR(15) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `registration` DATE NOT NULL,
  `id_recommender` INT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_recommender_idx` (`id_recommender` ASC) VISIBLE,
  CONSTRAINT `fk_recommender`
    FOREIGN KEY (`id_recommender`)
    REFERENCES `Customers` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Employees`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Employees` ;

CREATE TABLE IF NOT EXISTS `Employees` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sales`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Sales` ;

CREATE TABLE IF NOT EXISTS `Sales` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_glasses` INT UNSIGNED NOT NULL,
  `id_customer` INT UNSIGNED NOT NULL,
  `sale_date` DATE NOT NULL,
  `id_salesman` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `id_salesman`, `id_customer`, `id_glasses`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_salesman_idx` (`id_salesman` ASC) VISIBLE,
  INDEX `fk_customer_idx` (`id_customer` ASC) VISIBLE,
  INDEX `fk_glases_idx` (`id_glasses` ASC) VISIBLE,
  CONSTRAINT `fk_salesman`
    FOREIGN KEY (`id_salesman`)
    REFERENCES `Employees` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_customer`
    FOREIGN KEY (`id_customer`)
    REFERENCES `Customers` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_glases`
    FOREIGN KEY (`id_glasses`)
    REFERENCES `Glasses` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
